import React from 'react'
import {
  FileText,
  Printer,
  X,
  Building2,
  ShieldCheck,
  AlertTriangle,
  Radio,
  CheckCircle2,
  Download,
  Calendar,
  MapPin
} from 'lucide-react'

export default function SitrepGeneratorModal({ isOpen, onClose }) {
  if (!isOpen) return null

  const handlePrint = () => {
    window.print()
  }

  const currentDate = new Date().toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  })

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm overflow-y-auto">
      <div className="relative w-full max-w-4xl max-h-[90vh] bg-slate-900 border border-emerald-500/30 rounded-3xl shadow-2xl flex flex-col overflow-hidden text-slate-100">
        {/* Modal Top Bar */}
        <div className="px-6 py-4 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-2xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-black text-white flex items-center gap-2">
                Automated State Epidemiological Situation Report (SITREP)
                <span className="px-2 py-0.5 rounded-full bg-emerald-950 text-emerald-300 text-[10px] font-bold border border-emerald-500/30">
                  MSInS / DAH GovTech
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                1-click official intelligence briefing ready for State Directorate and District Collectors
              </p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Document Body */}
        <div className="p-6 overflow-y-auto space-y-6 flex-1 print:bg-white print:text-black">
          <div className="p-6 rounded-2xl bg-white text-slate-900 shadow-xl border border-slate-300 space-y-6 print:shadow-none print:border-none">
            {/* Gov Header */}
            <div className="text-center border-b-2 border-emerald-900 pb-4 space-y-1">
              <div className="text-xs font-black uppercase tracking-widest text-emerald-800">
                GOVERNMENT OF MAHARASHTRA • DEPARTMENT OF ANIMAL HUSBANDRY
              </div>
              <h1 className="text-xl font-black text-slate-900">
                STATE LIVESTOCK HEALTH SURVEILLANCE & OUTBREAK SITUATION REPORT (SITREP #04)
              </h1>
              <p className="text-xs font-bold text-slate-600">
                Pune Division Epidemiological Intelligence Command • Generated by PASHURAKSHA AI Platform
              </p>
              <div className="flex justify-center items-center space-x-6 text-[11px] text-slate-500 pt-1">
                <span><strong>Date:</strong> {currentDate}</span>
                <span><strong>Classification:</strong> OFFICIAL / IMMEDIATE ACTION</span>
                <span><strong>Epicenter:</strong> Baramati Block (18.1515° N, 74.5772° E)</span>
              </div>
            </div>

            {/* Executive KPI Summary */}
            <div className="grid grid-cols-4 gap-3 text-center">
              <div className="p-3 bg-slate-50 rounded-xl border border-slate-200">
                <span className="text-[10px] text-slate-500 block uppercase font-bold">Monitored Livestock</span>
                <strong className="text-lg font-black text-slate-900">18,450 Head</strong>
              </div>
              <div className="p-3 bg-rose-50 rounded-xl border border-rose-200">
                <span className="text-[10px] text-rose-600 block uppercase font-bold">Active Cases</span>
                <strong className="text-lg font-black text-rose-700">34 Head (FMD)</strong>
              </div>
              <div className="p-3 bg-emerald-50 rounded-xl border border-emerald-200">
                <span className="text-[10px] text-emerald-700 block uppercase font-bold">Ring Vaccination</span>
                <strong className="text-lg font-black text-emerald-700">71.0% Covered</strong>
              </div>
              <div className="p-3 bg-purple-50 rounded-xl border border-purple-200">
                <span className="text-[10px] text-purple-700 block uppercase font-bold">Case Fatality (CFR)</span>
                <strong className="text-lg font-black text-purple-700">0.0% (Zero Mortality)</strong>
              </div>
            </div>

            {/* Section 1: Epidemiological Context */}
            <div className="space-y-2 text-xs text-slate-800 leading-relaxed">
              <h3 className="text-sm font-black text-emerald-950 border-b border-emerald-200 pb-1">
                1. Epidemiological Assessment & Pathogen Confirmation
              </h3>
              <p>
                On 28th August 2026, anomalous clusters of vesicular oral ulcerations, excessive salivation, and high fever were algorithmically flagged by the <strong>Pashuraksha AI Spatial Surveillance Engine</strong> in Baramati. Subsequent RT-PCR testing by the Western Maharashtra Regional Disease Diagnostic Laboratory confirmed <strong>Foot and Mouth Disease Virus (Serotype O)</strong>.
              </p>
            </div>

            {/* Section 2: Containment Measures Undertaken */}
            <div className="space-y-2 text-xs text-slate-800">
              <h3 className="text-sm font-black text-emerald-950 border-b border-emerald-200 pb-1">
                2. Containment Cordon & Ring Immunization Status
              </h3>
              <div className="grid grid-cols-2 gap-3">
                <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl space-y-1">
                  <strong className="text-slate-900 block text-[11px]">5 km Inner Containment Ring:</strong>
                  <p className="text-[11px] text-slate-600">
                    • 6 Mobile Rapid Response Units (RRU) deployed.<br />
                    • 4,120 of 5,800 susceptible cattle/buffalo vaccinated.<br />
                    • Cattle markets & weekly haats in Baramati suspended.
                  </p>
                </div>
                <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl space-y-1">
                  <strong className="text-slate-900 block text-[11px]">10 km Buffer Surveillance Ring:</strong>
                  <p className="text-[11px] text-slate-600">
                    • Active fever surveillance in Shirur & Indapur.<br />
                    • Disinfectant footbaths (4% Na2CO3) mandated at all sheds.<br />
                    • Cold chain IoT telemetry maintained at 3.4°C – 4.8°C.
                  </p>
                </div>
              </div>
            </div>

            {/* Section 3: Field Directives */}
            <div className="space-y-2 text-xs text-slate-800">
              <h3 className="text-sm font-black text-emerald-950 border-b border-emerald-200 pb-1">
                3. Mandatory Operational Directives
              </h3>
              <ol className="list-decimal list-inside space-y-1 text-[11px] text-slate-700">
                <li>All Pashu Sakhis to complete 100% census of dairy sheds within 5km radius by 31st August.</li>
                <li>Daily SMS & WhatsApp alerts to be dispatched via District Broadcast Hub.</li>
                <li>Ensure zero milk collection from symptomatic cows in compliance with statutory withholding guidelines.</li>
              </ol>
            </div>

            {/* Signatures */}
            <div className="pt-6 border-t border-slate-300 grid grid-cols-2 text-xs text-slate-700">
              <div>
                <p className="font-bold text-slate-900">Dr. Vivek Kulkarni, B.V.Sc & A.H.</p>
                <p className="text-[10px] text-slate-500">Epidemiological Officer, Baramati Sub-Division</p>
              </div>
              <div className="text-right">
                <p className="font-bold text-slate-900">Dr. Sanjay More, M.V.Sc</p>
                <p className="text-[10px] text-slate-500">District Animal Husbandry Officer, Pune</p>
                <p className="text-[9px] text-emerald-700 font-bold">Government of Maharashtra</p>
              </div>
            </div>
          </div>
        </div>

        {/* Modal Actions */}
        <div className="px-6 py-4 bg-slate-950 border-t border-slate-800 flex items-center justify-between">
          <span className="text-xs text-slate-400">
            Validated by Pashuraksha AI State Epidemiological Intelligence Engine
          </span>
          <div className="flex items-center space-x-3">
            <button
              onClick={handlePrint}
              className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold transition flex items-center gap-2 border border-slate-700"
            >
              <Printer className="w-4 h-4" /> Print / Export Official PDF
            </button>
            <button
              onClick={onClose}
              className="px-5 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold transition"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
